# This means we only build and/or fetch these specific languages
# use-grammars = { only = [ "rust", "c", "cpp" ] }

[[language]]
# DO NOT FORGET: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
name = "cpp"
auto-format = true
# file-types = ["cpp", "h"]
# Using clang-format-15 for ARM64
# args = ["--style=Google"]
# formatting should be handled by clangd-15
# formatter = { command = 'clang-format-15' }
formatter = { command = 'clangd-15' }
# Setting indent is handled by the LSP
# indent = { tab-width = 4, unit = "    " }
# language-servers = [ "clangd" ]
# debugger = { command = "lldb-15" }

[[language]]
name = "rust"
auto-format = true
# file-types = ["rs"]
formatter = { command = "rustfmt" }
indent = { tab-width = 4, unit = "    " }
language-servers = [ "rust-analyzer" ]

# Using installed clangd-15 over regular clangd
[language-server.clangd]
command = "clangd-15"

# Setting up rust lsp
[language-server.rust-analyzer]
# command = "rust-analyzer"
check.command = "clippy"

[[grammar]]
name = "cpp"
source = { git = "https://github.com/tree-sitter/tree-sitter-cpp", rev = "30d2fa385735378388a55917e2910965fce19748" }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "6b7d1fc73ded57f73b1619bcf4371618212208b1" }

[[grammar]]
name = "html"
source = { git = "https://github.com/tree-sitter/tree-sitter-html" }

[[debugger]]
name = "lldb-dap"
transport = "stdio"
command = "lldb-15"

